# === PRODUKTION (LIVE SERVER) ===
spring:
  jpa:
    show-sql: false # SQL ausblenden (spart extrem viel Server-Leistung!)
    hibernate:
      ddl-auto: validate # Auf Prod darf Hibernate NIEMALS Tabellen ändern!

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

logging:
  level:
    root: INFO

app:
  keycloak:
    server-url_docker: ${KEYCLOAK_AUTH_SERVER_URL:http://hanmaumApp-keycloak:8090}
    realm: ${KEYCLOAK_REALM}
    admin-client-id: ${KEYCLOAK_BACKEND_CLIENT_ID}
    admin-client-secret: ${KEYCLOAK_BACKEND_CLIENT_SECRET}
