server:
  port: 8080

api:
  prefix: /api/v1

spring:
  application:
    name: church-dn-backend
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  profiles:
    active: dev